# Partiamo da un'immagine Node.js leggera
FROM node:20-alpine

# Imposta la cartella di lavoro
WORKDIR /app

# Copia solo i file delle dipendenze per sfruttare la cache di Docker
COPY package*.json ./

# Installa TUTTE le dipendenze, incluse quelle di sviluppo come nodemon
RUN npm install

# Copia il resto del codice sorgente
COPY . .

# Esponi la porta interna del container
EXPOSE 8080

# Usa il comando "dev" che abbiamo definito per avviare con nodemon
CMD [ "npm", "run", "dev" ]